name: ndesa_mobile
description: "NDESA Mobile - Platform GovTech Hybrid untuk Desa"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.0.0
  
  # HTTP & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^10.0.1
  
  # Image & File
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  
  # Other Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.2+1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

# Force intl to use version from Flutter SDK
dependency_overrides:
  intl: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/Splash-Sreen/

  
  # Fonts
  # Google Fonts will be used via google_fonts package

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/LogoNdesa.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#050708"
  android_12:
    color: "#050708"
  android: true
  ios: true
